ssSettings = 'Settings/';
ssLastConfig = 'LastConfig/';
ssScriptManager = 'ScriptManager/';

ssUpdater = 'Updater/';
ssFonts = 'Fonts/';
ssIncludes = 'Includes/';
ssInterpreter = 'Interpreter/';
ssTabs = 'Tabs/';
ssColourPicker = 'ColourPicker/';
ssScripts = 'Scripts/';
ssExtensions = 'Extensions/';
ssMainForm = 'MainForm/';
ssSourceEditor = 'SourceEditor/';
ssTray = 'Tray/';
ssConsole = 'Console/';
ssNews = 'News/';
ssPlugins = 'Plugins/';
ssNotes = 'Notes/';
ssMisc = 'Misc/';
ssCodeInsight = 'CodeInsight/';
ssFunctionList = 'FunctionList/';

ssCheckUpdate = ssSettings + ssUpdater + 'CheckForUpdates';
ssCheckUpdateMinutes = ssSettings + ssUpdater + 'CheckEveryXMinutes';
ssUpdaterLink = ssSettings + ssUpdater + 'RemoteLink';
ssUpdaterVersionLink = ssSettings + ssUpdater + 'RemoteVersionLink';
ssAutomaticallyUpdate = ssSettings + ssUpdater + 'AutomaticallyUpdate';
ssUpdaterReleaseChannel = ssSettings + ssUpdater + 'ReleaseChannel';

ssLoadFontsOnStart = ssSettings + ssFonts + 'LoadOnStartUp';
ssFontsCheckForUpdates = ssSettings + ssFonts + 'CheckForUpdates';
ssFontsVersion = ssSettings + ssFonts + 'Version';
ssFontsLink = ssSettings + ssFonts + 'UpdateLink';
ssFontsVersionLink = ssSettings + ssFonts + 'VersionLink';
ssFontsPath = ssSettings + ssFonts + 'Path';

ssIncludesPath = ssSettings + ssIncludes + 'Path';
ssInterpreterType = ssSettings + ssInterpreter + 'Type';
ssInterpreterAllowSysCalls = ssSettings + ssInterpreter + 'AllowSysCalls';

ssTabsOpenNextOnClose = ssSettings + ssTabs + 'OpenNextOnClose';
ssTabsOpenScriptInNewTab = ssSettings + ssTabs + 'OpenScriptInNewTab';
ssTabsCheckBeforeOpen = ssSettings + ssTabs + 'CheckTabsBeforeOpen';

ssColourPickerShowHistoryOnPick = ssSettings + ssColourPicker + 'ShowHistoryOnPick';
ssColourPickerAddToHistoryOnPick = ssSettings + ssColourPicker + 'AddToHistoryOnPick';
ssColourPickerAddCoordinateToClipBoard = ssSettings + ssColourPicker + 'AddCoordinateToClipBoard';
ssColourPickerAddColourToClipBoard = ssSettings + ssColourPicker + 'AddColourToClipBoard';

ssScriptsPath = ssSettings + ssScripts + 'Path';

ssCodeHintsShowAutomatically = ssSettings + ssCodeInsight + 'CodeHints/ShowAutomatically';
ssCodeCompletionShowAutomatically = ssSettings + ssCodeInsight + 'CodeCompletion/ShowAutomatically';

ssShowBalloonHints = ssSettings + 'ShowBalloonHints';

ssSourceEditorLazColors = ssSettings + ssSourceEditor + 'LazColors';
ssSourceEditorCaretPastEOL = ssSettings + ssSourceEditor + 'CaretPastEOL';
ssSourceEditorFont = ssSettings + ssSourceEditor + 'Font/';
ssSourceEditorDefScriptPath = ssSettings + ssSourceEditor + 'DefScriptPath';
ssSourceEditorHighlighterPath = ssSettings + ssSourceEditor + 'Highlighter';

ssNewsLink = ssSettings + ssNews + 'URL';
ssPluginsPath = ssSettings + ssPlugins + 'Path';

ssExtensionsExtensionN = ssExtensions + 'Extension';
ssExtensionsPath = ssSettings + ssExtensions + 'Path';
ssExtensionsCount = ssExtensions + 'ExtensionCount';
ssExtensionsFileExtension = ssSettings + ssExtensions + 'FileExtension';

ssTrayAlwaysVisible = ssSettings + ssTray + 'AlwaysVisible';

ssConsoleVisible = ssLastConfig + ssConsole + 'Visible';

ssMainFormPosition = ssLastConfig + ssMainForm + 'Position';
ssMainFormState = ssLastConfig + ssMainForm + 'State';
ssMainFormNormalSize = ssSettings + ssMainForm + 'NormalSize';
ssFunctionListShown = ssLastConfig + ssMainForm + 'FunctionListShown';

ssCodeInsightShowHidden = ssSettings + ssCodeInsight + 'ShowHidden';
ssFunctionListShowOnStart = ssSettings + ssCodeInsight + ssFunctionList + 'ShowOnStart';

ssMaxRecentFiles = ssSettings + 'General/MaxRecentFiles';
ssRecentFiles = ssLastConfig + ssMainForm + 'RecentFiles';
ssRecentFilesCount = ssLastConfig + ssMainForm + 'RecentFiles/Count';
ssRecentFile = ssLastConfig + ssMainForm + 'RecentFiles/File';

ssNotesContent = ssSettings + ssNotes + 'Content';
ssNotesVisible = ssSettings + ssNotes + 'Visible';

ssFileBrowserVisible = ssSettings + 'FileBrowser/Visible';

ssMiscRestartScriptIfStarted = ssSettings + ssMisc + 'RestartScriptIfStarted';
ssMiscWarnIfRunning = ssSettings + ssMisc + 'WarnIfRunning';
ssMiscWarnIfModified = ssSettings + ssMisc + 'WarnIfModified';
ssSaveScriptOnCompile = ssSettings + ssMisc + 'SaveScriptOnCompile';

ssSMURL = ssScriptManager + 'URL';
ssSMPath = ssScriptManager + 'Path';
ssSMFile = ssScriptManager + 'File';
ssFRun = ssScriptManager + 'FirstRun';
