SEARCH_DIR("C:\Users\OllyC\Desktop\Code\Simba-wip2\Third-Party\lape\extensions\ffi\bin\win64\")
SEARCH_DIR(".\")
SEARCH_DIR("C:\Users\OllyC\Desktop\Code\Simba-wip2\Third-Party\")
SEARCH_DIR("C:\Users\OllyC\Desktop\Code\Simba-wip2\Third-Party\lape\")
SEARCH_DIR("C:\Users\OllyC\Desktop\Code\Simba-wip2\Third-Party\lape\extensions\ffi\")
SEARCH_DIR(".\script\imports\")
SEARCH_DIR(".\script\imports\lcl\")
SEARCH_DIR(".\script\")
SEARCH_DIR(".\ide\")
SEARCH_DIR(".\ide\codetools\")
SEARCH_DIR("C:\lazarus\components\synedit\units\x86_64-win64\win32\")
SEARCH_DIR("C:\lazarus\components\lazcontrols\lib\x86_64-win64\win32\")
SEARCH_DIR("C:\lazarus\components\anchordocking\units\x86_64-win64\win32\")
SEARCH_DIR("C:\lazarus\lcl\units\x86_64-win64\win32\")
SEARCH_DIR("C:\lazarus\lcl\units\x86_64-win64\")
SEARCH_DIR("C:\lazarus\components\lazedit\lib\x86_64-win64\")
SEARCH_DIR("C:\lazarus\components\freetype\lib\x86_64-win64\")
SEARCH_DIR("C:\lazarus\components\lazutils\lib\x86_64-win64\")
SEARCH_DIR("C:\lazarus\packager\units\x86_64-win64\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\httpd22\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\zlib\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-jedi\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\webidl\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\vcl-compat\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\utils-pas2js\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\unzip\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\tplylib\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\tcl\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\symbolic\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\sqlite\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\sdl\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-unicode\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-objpas\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-generics\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-extra\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-console\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\rsvg\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\regexpr\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\ptc\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\postgres\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\pastojs\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\oracle\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\openssl\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\opengles\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\opengl\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\opencl\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\odbc\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\odata\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\nvapi\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\numlib\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\mysql\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\mad\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\libvlc\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\libusb\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\libtar\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\libmicrohttpd\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\libgd\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\libffi\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\libenet\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\libcurl\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\jni\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\imagemagick\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\ibase\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\httpd24\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\hermes\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\hash\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\gtk2\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\gtk1\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\graph\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\googleapi\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\gnutls\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\gdbint\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fv\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fppkg\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fpmkunit\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fpindexer\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fpgtk\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fftw\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-xml\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-web\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-stl\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-sound\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-sdo\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-res\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-report\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-registry\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-process\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-pdf\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-passrc\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-net\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-json\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-js\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-fpcunit\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-extra\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-db\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-base\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\fastcgi\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\dblib\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\chm\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\cdrom\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\cairo\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\bzip2\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\units\x86_64-win64\")
SEARCH_DIR("C:\lazarus\fpc\3.2.2\bin\x86_64-win64\")
INPUT(
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\sysinit.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\Simba.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\Simba.obj
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\system.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\lnfodwrf.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\exeinfo.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\strings.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\windows.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\objpas.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\fpintres.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\mormot2_mm.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.init.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\classes.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\sysutils.o
C:\lazarus\lcl\units\x86_64-win64\win32\interfaces.o
C:\lazarus\lcl\units\x86_64-win64\forms.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.base.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_main.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_about.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_imagestring.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_filebrowser.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_notes.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_settings.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_openexample.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_shapebox.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_backups.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_findinfiles.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_downloadsimba.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_package.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_colorpickhistory.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.plugin_dump.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_runner.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.initializations.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_analytics.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.openssl.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_colorpicker.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_windowselector.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_areaselector.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_mainmenubar.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_maintoolbar.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_mainstatusbar.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_functionlist.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_output.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\math.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\rtlconsts.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\types.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\typinfo.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\sysconst.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\windirs.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazutf8.o
C:\lazarus\lcl\units\x86_64-win64\interfacebase.o
C:\lazarus\components\lazutils\lib\x86_64-win64\fpcadds.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-objpas\strutils.o
C:\lazarus\components\lazutils\lib\x86_64-win64\translations.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-json\jsonscanner.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-json\jsonparser.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-json\fpjson.o
C:\lazarus\components\lazutils\lib\x86_64-win64\fileutil.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazfileutils.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lconvencoding.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazloggerbase.o
C:\lazarus\components\lazutils\lib\x86_64-win64\avglvltree.o
C:\lazarus\components\lazutils\lib\x86_64-win64\stringhashlist.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-json\jsonreader.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-objpas\variants.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-base\contnrs.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-objpas\varutils.o
C:\lazarus\components\lazutils\lib\x86_64-win64\masks.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazutilsstrconsts.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\shlobj.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\activex.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\shellapi.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\commctrl.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\ctypes.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\dos.o
C:\lazarus\components\lazutils\lib\x86_64-win64\codepagescommon.o
C:\lazarus\components\lazutils\lib\x86_64-win64\codepagesasian.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazclasses.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazmethodlist.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-base\avl_tree.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazdbglog.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpimage.o
C:\lazarus\lcl\units\x86_64-win64\lclproc.o
C:\lazarus\lcl\units\x86_64-win64\lcltype.o
C:\lazarus\lcl\units\x86_64-win64\lmessages.o
C:\lazarus\lcl\units\x86_64-win64\lclplatformdef.o
C:\lazarus\lcl\units\x86_64-win64\intfgraphics.o
C:\lazarus\lcl\units\x86_64-win64\themes.o
C:\lazarus\lcl\units\x86_64-win64\wsreferences.o
C:\lazarus\components\lazutils\lib\x86_64-win64\integerlist.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazutilities.o
C:\lazarus\components\lazutils\lib\x86_64-win64\graphtype.o
C:\lazarus\components\lazutils\lib\x86_64-win64\graphmath.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazversion.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazutf16.o
C:\lazarus\components\lazutils\lib\x86_64-win64\laztracer.o
C:\lazarus\lcl\units\x86_64-win64\lclstrconsts.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-objpas\system.uitypes.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\messages.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpreadbmp.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpwritebmp.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\bmpcomn.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpreadpng.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpwritepng.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpreadtiff.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpwritetiff.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fptiffcmn.o
C:\lazarus\lcl\units\x86_64-win64\lclversion.o
C:\lazarus\lcl\units\x86_64-win64\icnstypes.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpimgcmn.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\pngcomn.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\zstream.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\zbase.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\gzio.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\hash\crc.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\zdeflate.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\zinflate.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\trees.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\adler.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\infblock.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\infutil.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\infcodes.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\inftrees.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\inffast.o
C:\lazarus\lcl\units\x86_64-win64\graphics.o
C:\lazarus\lcl\units\x86_64-win64\lclintf.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpcanvas.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpreadpnm.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpwritepnm.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpreadjpeg.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpwritejpeg.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpreadgif.o
C:\lazarus\lcl\units\x86_64-win64\lresources.o
C:\lazarus\lcl\units\x86_64-win64\lclrescache.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\clipping.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jpeglib.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdapimin.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdatasrc.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdapistd.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jmorecfg.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdeferr.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jinclude.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jerror.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jmemmgr.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdmarker.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdinput.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jcomapi.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jutils.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jmemnobs.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdmaster.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdcolor.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdsample.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdpostct.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jddctmgr.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdphuff.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdhuff.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdcoefct.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdmainct.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jquant1.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jquant2.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdmerge.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdct.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jidctfst.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jidctint.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jidctflt.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jidctred.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jcapistd.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jcapimin.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jdatadst.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jcparam.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jcinit.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jcmarker.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jcphuff.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jchuff.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jcmaster.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jccolor.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jcsample.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jcprepct.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jcdctmgr.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jccoefct.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jcmainct.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jfdctint.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jfdctfst.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\pasjpeg\jfdctflt.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazconfigstorage.o
C:\lazarus\components\lazutils\lib\x86_64-win64\dynqueue.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazstringutils.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-base\syncobjs.o
C:\lazarus\components\lazutils\lib\x86_64-win64\utf8process.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazsysutils.o
C:\lazarus\components\lazutils\lib\x86_64-win64\maps.o
C:\lazarus\lcl\units\x86_64-win64\tmschema.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\fgl.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-process\process.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-process\pipes.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32int.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\multimon.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\uxtheme.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\dwmapi.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\character.o
C:\lazarus\lcl\units\x86_64-win64\controls.o
C:\lazarus\lcl\units\x86_64-win64\buttons.o
C:\lazarus\lcl\units\x86_64-win64\dialogs.o
C:\lazarus\lcl\units\x86_64-win64\stdctrls.o
C:\lazarus\lcl\units\x86_64-win64\menus.o
C:\lazarus\lcl\units\x86_64-win64\comctrls.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32def.o
C:\lazarus\lcl\units\x86_64-win64\spin.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\unicodedata.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\unicodenumtable.o
C:\lazarus\lcl\units\x86_64-win64\imglist.o
C:\lazarus\lcl\units\x86_64-win64\propertystorage.o
C:\lazarus\lcl\units\x86_64-win64\actnlist.o
C:\lazarus\lcl\units\x86_64-win64\lclclasses.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fpimgcanv.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\fppixlcanv.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\pixtools.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-image\ellipses.o
C:\lazarus\lcl\units\x86_64-win64\wslclclasses.o
C:\lazarus\lcl\units\x86_64-win64\wsimglist.o
C:\lazarus\lcl\units\x86_64-win64\wsproc.o
C:\lazarus\lcl\units\x86_64-win64\wsfactory.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-base\rttiutils.o
C:\lazarus\lcl\units\x86_64-win64\wsmenus.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-base\custapp.o
C:\lazarus\lcl\units\x86_64-win64\customtimer.o
C:\lazarus\lcl\units\x86_64-win64\clipbrd.o
C:\lazarus\lcl\units\x86_64-win64\helpintfs.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-base\singleinstance.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\chm\fasthtmlparser.o
C:\lazarus\lcl\units\x86_64-win64\wscontrols.o
C:\lazarus\lcl\units\x86_64-win64\wsforms.o
C:\lazarus\lcl\units\x86_64-win64\imagelistcache.o
C:\lazarus\components\lazutils\lib\x86_64-win64\textstrings.o
C:\lazarus\components\lazutils\lib\x86_64-win64\extendedstrings.o
C:\lazarus\lcl\units\x86_64-win64\wsstdctrls.o
C:\lazarus\lcl\units\x86_64-win64\wsbuttons.o
C:\lazarus\lcl\units\x86_64-win64\buttonpanel.o
C:\lazarus\lcl\units\x86_64-win64\extctrls.o
C:\lazarus\lcl\units\x86_64-win64\dialogres.o
C:\lazarus\lcl\units\x86_64-win64\popupnotifier.o
C:\lazarus\lcl\units\x86_64-win64\wsextctrls.o
C:\lazarus\lcl\units\x86_64-win64\toolwin.o
C:\lazarus\lcl\units\x86_64-win64\wscomctrls.o
C:\lazarus\lcl\units\x86_64-win64\wstoolwin.o
C:\lazarus\lcl\units\x86_64-win64\wsdialogs.o
C:\lazarus\lcl\units\x86_64-win64\taskdlgemulation.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-objpas\dateutils.o
C:\lazarus\lcl\units\x86_64-win64\wsspin.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32proc.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wsfactory.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wscontrols.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wsbuttons.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wsmenus.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wsstdctrls.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wsdialogs.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32themes.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32extra.o
C:\lazarus\lcl\units\x86_64-win64\lclmessageglue.o
C:\lazarus\lcl\units\x86_64-win64\calendar.o
C:\lazarus\lcl\units\x86_64-win64\extdlgs.o
C:\lazarus\lcl\units\x86_64-win64\checklst.o
C:\lazarus\lcl\units\x86_64-win64\grids.o
C:\lazarus\lcl\units\x86_64-win64\shellctrls.o
C:\lazarus\lcl\units\x86_64-win64\wscalendar.o
C:\lazarus\lcl\units\x86_64-win64\calcform.o
C:\lazarus\lcl\units\x86_64-win64\wsextdlgs.o
C:\lazarus\lcl\units\x86_64-win64\wschecklst.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-xml\htmldefs.o
C:\lazarus\lcl\units\x86_64-win64\maskedit.o
C:\lazarus\components\lazutils\lib\x86_64-win64\dynamicarray.o
C:\lazarus\components\lazutils\lib\x86_64-win64\laz2_xmlcfg.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lcsvutils.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\imm.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazfilecache.o
C:\lazarus\components\lazutils\lib\x86_64-win64\laz2_dom.o
C:\lazarus\components\lazutils\lib\x86_64-win64\laz2_xmlread.o
C:\lazarus\components\lazutils\lib\x86_64-win64\laz2_xmlwrite.o
C:\lazarus\components\lazutils\lib\x86_64-win64\laz2_xmlutils.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-base\uriparser.o
C:\lazarus\lcl\units\x86_64-win64\wsgrids.o
C:\lazarus\lcl\units\x86_64-win64\wsshellctrls.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wscalendar.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wschecklst.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wscomctrls.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wsextctrls.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wsextdlgs.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wsforms.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wsgrids.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wsimglist.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wsshellctrls.o
C:\lazarus\lcl\units\x86_64-win64\win32\win32wsspin.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\commdlg.o
C:\lazarus\components\anchordocking\units\x86_64-win64\win32\anchordockpanel.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.settings.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_events.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.image.o
C:\lazarus\components\anchordocking\units\x86_64-win64\win32\anchordockstorage.o
C:\lazarus\components\anchordocking\units\x86_64-win64\win32\anchordockstr.o
C:\lazarus\components\anchordocking\units\x86_64-win64\win32\anchordocking.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-base\inifiles.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.containers.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synedit.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.encoding.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.env.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_docgenerator.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_theme.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.misc.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\lazsynimmbase.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\lazsynimm.o
C:\lazarus\lcl\units\x86_64-win64\stdactns.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synedittypes.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditsearch.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditkeycmds.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmousecmds.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmiscprocs.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditpointclasses.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synbeautifier.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmarks.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmarkup.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmarkuphighall.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmarkupbracket.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmarkupwordgroup.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmarkupctrlmouselink.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmarkupspecialline.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmarkupselection.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmarkupspecialchar.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synedittextbase.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\lazsynedittext.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synedittextbuffer.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditlines.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synedittexttrimmer.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synedittexttabexpander.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synedittextdoublewidthchars.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditfoldedview.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syngutterbase.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syngutter.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmiscclasses.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synedithighlighter.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\lazsyntextarea.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syntextdrawer.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synedittextbidichars.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synguttercodefolding.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syngutterchanges.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syngutterlinenumber.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synguttermarks.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syngutterlineoverview.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-registry\registry.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditstrconst.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\lazsyneditmousecmdstypes.o
C:\lazarus\lcl\units\x86_64-win64\graphutil.o
C:\lazarus\lcl\units\x86_64-win64\lazcanvas.o
C:\lazarus\lcl\units\x86_64-win64\lazregions.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\regexpr\regexpr.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synedithighlighterfoldbase.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\hash\sha1.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\hash\hmac.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\fpbasenenc.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\hash\md5.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.fs.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.hash.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\mormor2_xxhash32.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\fpsha256.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\fpsha512.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\fphashutils.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.vartype_string.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.vartype_ordarray.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.array_algorithm.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.container_dict.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.math.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_codetools_parser.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.dialog.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_commands.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_codetools_base.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_codetools_paslexer.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_codetools_pasparser.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.threading.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\numcpulib.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_images.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_utils.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.process.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.baseclass.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.nativeinterface.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.nativeinterface_windows.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-jedi\jwapsapi.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\mmsystem.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.vartype_windowhandle.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.vartype_box.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-jedi\jwawintype.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-jedi\jwawinnt.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.random.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.geometry.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.vartype_point.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.image_textdrawer.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.colormath.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.vartype_polygon.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.vartype_quad.o
C:\lazarus\components\freetype\lib\x86_64-win64\lazfreetypefpimagedrawer.o
C:\lazarus\components\freetype\lib\x86_64-win64\easylazfreetype.o
C:\lazarus\components\freetype\lib\x86_64-win64\lazfreetype.o
C:\lazarus\components\freetype\lib\x86_64-win64\ttraster.o
C:\lazarus\components\freetype\lib\x86_64-win64\tttypes.o
C:\lazarus\components\freetype\lib\x86_64-win64\ttobjs.o
C:\lazarus\components\freetype\lib\x86_64-win64\tterror.o
C:\lazarus\components\freetype\lib\x86_64-win64\ttcalc.o
C:\lazarus\components\freetype\lib\x86_64-win64\ttmemory.o
C:\lazarus\components\freetype\lib\x86_64-win64\tttables.o
C:\lazarus\components\freetype\lib\x86_64-win64\ttcache.o
C:\lazarus\components\freetype\lib\x86_64-win64\ttfile.o
C:\lazarus\components\freetype\lib\x86_64-win64\ttcmap.o
C:\lazarus\components\freetype\lib\x86_64-win64\ttload.o
C:\lazarus\components\freetype\lib\x86_64-win64\ttgload.o
C:\lazarus\components\freetype\lib\x86_64-win64\ttkern.o
C:\lazarus\components\freetype\lib\x86_64-win64\ttinterp.o
C:\lazarus\components\freetype\lib\x86_64-win64\ttprofile.o
C:\lazarus\components\freetype\lib\x86_64-win64\lazfreetypefontcollection.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.image_utils.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.colormath_conversion.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.vartype_triangle.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.vartype_circle.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.vartype_pointarray.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.vector.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.container_kdpointtree.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.vartype_matrix.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.container_heaparray.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.image_lazbridge.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.image_resizerotate.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.image_stringconv.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.image_filters.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.image_draw.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.image_drawmatrix.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.colormath_distance.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.zip.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\paszlib\zipper.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_button.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\atscrollbar.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\atcanvasprimitives.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_package.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.httpclient.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-web\fphttpclient.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-net\ssockets.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.json.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-web\httpdefs.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-base\base64.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-extra\sockets.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-extra\winsock2.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-net\resolve.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-extra\winsock.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-web\httpprotocol.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-net\sslsockets.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-net\sslbase.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.jsonparser.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\openssl\openssl.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\castle_gz.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\dynlibs.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_package_endpointgithub.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_package_endpointcustom.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-xml\xmlread.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-xml\dom.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-xml\xmlutils.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-xml\xmlreader.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-xml\xmltextreader.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-xml\dtdmodel.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_vars.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_scriptbackup.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_associate.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_debugimage.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_dockinghelpers.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_dtmeditor.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_controller.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_scripttabs.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.aca.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_tab.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_output_components.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_tabcontrol.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synhighlighterpas.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_completionbox.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_paramhint.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_attributes.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_modifiedlinegutter.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_synedit.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\syncompletion_simba.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_codetools_insight.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditplugins.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_scrollbar.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_codetools_includes.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_codetools_exprparser.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_codetools_arrayhelpers.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_codetools_generics.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_plugin.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_compiler.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_pluginmethods.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpcompiler.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lptypes.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpvartypes.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lptree.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpffiwrappers.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\ffi.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpparser.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpmessages.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpcodeemitter.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpinterpreter_types.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpvartypes_ord.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpvartypes_array.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpvartypes_object.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpinternalmethods.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpeval.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpeval_extra.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpvartypes_helper.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpvartypes_record.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpinternalmethods_algorithm.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpinterpreter.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpinterpreter_debugevals.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\lpffi.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.externalcanvas.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_pluginloader.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_codetools_setup.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditmarkupfoldcoloring.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditwrappedview.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\syneditviewedlinemap.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazlistclasses.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_blockcompletion.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_commentblock.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_mousewheelzoom.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_multicaret.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_codecomplete.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editorcarethistory.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.editor_highlighter.o
C:\lazarus\components\synedit\units\x86_64-win64\win32\synpluginmulticaret.o
C:\lazarus\components\lazutils\lib\x86_64-win64\lazloggerdummy.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\attabs.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\atflatcontrols_separator.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_showdeclaration.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_scriptcommunication.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_popupmenu.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_findpanel.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_findreplace.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_edit.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_simpleformatter.o
C:\lazarus\lcl\units\x86_64-win64\xmlpropstorage.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-xml\xmlconf.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\fcl-xml\xmlwrite.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_simplelexer.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_toolbar.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.frame_settings_editor.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.frame_settings_editorcolors.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.frame_settings_editorcustomtokenattri.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.frame_settings_editordefault.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.frame_settings_editorfont.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.frame_settings_editorkeystrokes.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.frame_settings_general.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.frame_settings_output.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.frame_settings_backup.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.frame_settings_codetools.o
C:\lazarus\components\lazcontrols\lib\x86_64-win64\win32\dividerbevel.o
C:\lazarus\lcl\units\x86_64-win64\colorbox.o
C:\lazarus\lcl\units\x86_64-win64\editbtn.o
C:\lazarus\lcl\units\x86_64-win64\groupededit.o
C:\lazarus\lcl\units\x86_64-win64\calendarpopup.o
C:\lazarus\lcl\units\x86_64-win64\timepopup.o
C:\lazarus\components\lazcontrols\lib\x86_64-win64\win32\treefilteredit.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\atlistbox.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_buttonpanel.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_ipc.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_debugimg.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_imagebox.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_statusbar.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_imageboxcanvas.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.dtm.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.target.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_imageboxdrawers.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.compress.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\mormot2_synlz.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\mormot2_rle.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.target_eios.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.target_window.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.target_image.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.target_plugin.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.target_movemouse.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.finder_color.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.finder_image.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.finder_dtm.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.colormath_distance_unrolled.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.multiprocessing.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.matchtemplate.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.matchtemplate_ccorr.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.matchtemplate_sqdiff.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.matchtemplate_ccoeff.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.matchtemplate_matrix.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.matchtemplate_helpers.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.fftpack4.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.fftpack4_core.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.datetime.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_codetools_debug.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_treeview.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_treeviewhint.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_editor_mousecommands.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\fileassoc.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.toolform.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_imageboxzoom.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_menubar.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_splitter.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_divider.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_notebook.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.functionlist_page.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.functionlistpage_contextmenu.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.colormath_aca.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.component_shapebox.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_package_components.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.form_packageinstall.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_package_installer.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.ide_package_autoupdater.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_communication.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_imports.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_compiler_sleepuntil.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_compiler_rtti.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_compiler_imagefromstring.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_genericmap.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_genericstringmap.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_genericheap.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_genericarraybuffer.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_base.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_variant.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_colormath.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_matrix.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_windowhandle.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_timing.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_datetime.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_encoding.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_file.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_process.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_target.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_math.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_misc.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_kdpointtree.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_kdtree.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_string.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_random.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_debugimage.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_web.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_threading.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_async.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_pixelocr.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_vector.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_quad.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_triangle.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_box.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_point.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_circle.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_polygon.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_image.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_externalcanvas.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_dtm.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_matchtemplate.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_json.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_imagebox.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_shapebox.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_lcl_system.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_lcl_graphics.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_lcl_controls.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_lcl_form.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_lcl_stdctrls.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_lcl_extctrls.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_lcl_comctrls.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.import_lcl_misc.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_objectutil.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.target_asyncmovemouse.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.resource.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_genericbase.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.container_kdtree.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.internetsocket.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\openssl\opensslsockets.o
C:\lazarus\fpc\3.2.2\units\x86_64-win64\openssl\fpopenssl.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.script_threading.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.http_async.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.fs_async.o
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\simba.pixelocr.o
C:\lazarus\lcl\units\x86_64-win64\inipropstorage.o
C:\lazarus\components\lazcontrols\lib\x86_64-win64\win32\listfilteredit.o
)
GROUP(
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\libimpsysinit.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\libimpsystem.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\libimpwindows.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\libimpfpintres.a
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\libimpmormot2_mm.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\libimpsysutils.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\libimpwindirs.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-objpas\libimpvarutils.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\libimpshlobj.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\libimpactivex.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\libimpshellapi.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\libimpcommctrl.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl\libimpdos.a
C:\lazarus\lcl\units\x86_64-win64\libimplclintf.a
C:\lazarus\lcl\units\x86_64-win64\win32\libimpwin32extra.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\libimpimm.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\libimpcommdlg.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-jedi\libimpjwapsapi.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-base\libimpmmsystem.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-jedi\libimpjwawintype.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\winunits-jedi\libimpjwawinnt.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-extra\libimpwinsock2.a
C:\lazarus\fpc\3.2.2\units\x86_64-win64\rtl-extra\libimpwinsock.a
C:\Users\OllyC\Desktop\Code\Simba-wip2\build\Default\x86_64-win64\libimpsimba.ide_editor_completionbox.a
)
INPUT(
C:\Users\OllyC\Desktop\Code\Simba-wip2\Third-Party\lape\extensions\ffi\bin\win64\libffi.a
C:\Users\OllyC\Desktop\Code\Simba-wip2\Third-Party\lape\extensions\ffi\bin\win64\libgcc.a
C:\Users\OllyC\Desktop\Code\Simba-wip2\Third-Party\lape\extensions\ffi\bin\win64\libmsvcrt.a
C:\Users\OllyC\Desktop\Code\Simba-wip2\Third-Party\lape\extensions\ffi\bin\win64\libkernel32.a
)
SEARCH_DIR("/usr/i686-pc-cygwin/lib"); SEARCH_DIR("/usr/lib"); SEARCH_DIR("/usr/lib/w32api");
OUTPUT_FORMAT(pei-x86-64)
ENTRY(_mainCRTStartup)
SECTIONS
{
  . = SIZEOF_HEADERS;
  . = ALIGN(__section_alignment__);
  .text  __image_base__ + ( __section_alignment__ < 0x1000 ? . : __section_alignment__ ) :
  {
    __text_start__ = . ;
    *(.init)
    *(.text .stub .text.* .gnu.linkonce.t.*)
    *(SORT(.text$*))
    *(.glue_7t)
    *(.glue_7)
    . = ALIGN(8);
     ___CTOR_LIST__ = .; __CTOR_LIST__ = . ;
    LONG (-1);
    LONG (-1);
    *(.ctors); *(.ctor); *(SORT(.ctors.*));  LONG (0);
    LONG (0);
     ___DTOR_LIST__ = .; __DTOR_LIST__ = . ;
    LONG (-1);
    LONG (-1);
    *(.dtors); *(.dtor); *(SORT(.dtors.*));  LONG (0);
    LONG (0);
     *(.fini)
    PROVIDE (etext = .);
    *(.gcc_except_table)
  }
  .data BLOCK(__section_alignment__) :
  {
    __data_start__ = . ;
    *(.data .data.* .gnu.linkonce.d.* .fpc*)
    *(.data2)
    *(SORT(.data$*))
    *(.jcr)
    PROVIDE (_tls_index = .);
    LONG (0);
    __data_end__ = . ;
    *(.data_cygwin_nocopy)
  }
  .rdata BLOCK(__section_alignment__) :
  {
    *(.rdata)
    *(.rdata.*)
    *(.rodata .rodata.* .gnu.linkonce.r.*)
    *(SORT(.rdata$*))
    *(.eh_frame)
    ___RUNTIME_PSEUDO_RELOC_LIST__ = .;
    __RUNTIME_PSEUDO_RELOC_LIST__ = .;
    *(.rdata_runtime_pseudo_reloc)
    ___RUNTIME_PSEUDO_RELOC_LIST_END__ = .;
    __RUNTIME_PSEUDO_RELOC_LIST_END__ = .;
  }
  .pdata BLOCK(__section_alignment__) : { *(.pdata) }
  .bss BLOCK(__section_alignment__) :
  {
    __bss_start__ = . ;
    *(.bss .bss.* .gnu.linkonce.b.*)
    *(SORT(.bss$*))
    *(COMMON)
    __bss_end__ = . ;
  }
  .edata BLOCK(__section_alignment__) : { *(.edata) }
  .idata BLOCK(__section_alignment__) :
  {
    SORT(*)(.idata$2)
    SORT(*)(.idata$3)
    /* These zeroes mark the end of the import list.  */
    LONG (0); LONG (0); LONG (0); LONG (0); LONG (0);
    SORT(*)(.idata$4)
    SORT(*)(.idata$5)
    SORT(*)(.idata$6)
    SORT(*)(.idata$7)
  }
  .CRT BLOCK(__section_alignment__) :
  {
    ___crt_xc_start__ = . ;
    *(SORT(.CRT$XC*))  /* C initialization */
    ___crt_xc_end__ = . ;
    ___crt_xi_start__ = . ;
    *(SORT(.CRT$XI*))  /* C++ initialization */
    ___crt_xi_end__ = . ;
    ___crt_xl_start__ = . ;
    *(SORT(.CRT$XL*))  /* TLS callbacks */
    /* ___crt_xl_end__ is defined in the TLS Directory support code */
    PROVIDE (___crt_xl_end__ = .);
    ___crt_xp_start__ = . ;
    *(SORT(.CRT$XP*))  /* Pre-termination */
    ___crt_xp_end__ = . ;
    ___crt_xt_start__ = . ;
    *(SORT(.CRT$XT*))  /* Termination */
    ___crt_xt_end__ = . ;
  }
  .tls BLOCK(__section_alignment__) :
  {
    ___tls_start__ = . ;
    *(.tls .tls.*)
    *(.tls$)
    *(SORT(.tls$*))
    ___tls_end__ = . ;
  }
  .rsrc BLOCK(__section_alignment__) :
  {
    *(.rsrc)
    *(SORT(.rsrc$*))
  }
  .reloc BLOCK(__section_alignment__) : { *(.reloc) }
  .stab BLOCK(__section_alignment__) (NOLOAD) : { *(.stab) }
  .stabstr BLOCK(__section_alignment__) (NOLOAD) : { *(.stabstr) }
  .debug_aranges BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_aranges) }
  .debug_pubnames BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_pubnames) }
  .debug_info BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_info) *(.gnu.linkonce.wi.*) }
  .debug_abbrev BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_abbrev) }
  .debug_line BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_line) }
  .debug_frame BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_frame) }
  .debug_str BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_str) }
  .debug_loc BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_loc) }
  .debug_macinfo BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_macinfo) }
  .debug_weaknames BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_weaknames) }
  .debug_funcnames BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_funcnames) }
  .debug_typenames BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_typenames) }
  .debug_varnames BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_varnames) }
  .debug_ranges BLOCK(__section_alignment__) (NOLOAD) : { *(.debug_ranges) }
}
