'function ExtractFilePath(const FileName: String): String; begin end;' + LineEnding +
'function ExtractFileDrive(const FileName: String): String; begin end;' + LineEnding +
'function ExtractFileName(const FileName: String): String; begin end;' + LineEnding +
'function ExtractFileExt(const FileName: String): String; begin end;' + LineEnding +
'function ExtractFileDir(const FileName: String): String; begin end;' + LineEnding +
'function ExpandFileName(const FileName: String): String; begin end;' + LineEnding +
'function ExtractRelativepath(const BaseName, DestName: String): String; begin end;' + LineEnding +
'function IncludeTrailingPathDelimiter(const Path: String) : String; begin end;' + LineEnding +
'function ExcludeTrailingPathDelimiter(const Path: String): String; begin end;' + LineEnding +
'function IncludeTrailingBackslash(const Path: String) : String; begin end;' + LineEnding +
'function ExcludeTrailingBackslash(const Path: String): String; begin end;' + LineEnding +
'function IncludeLeadingPathDelimiter(const Path : String) : String; begin end;' + LineEnding +
'function ExcludeLeadingPathDelimiter(const Path: String): String; begin end;';
