'const Pi: Extended = 3.14159265358979;' + LineEnding +
'function Min(x,y: Int64): Int64; overload; begin end;' + LineEnding +
'function Min(x,y: Extended): Extended; overload; begin end;' + LineEnding +
'function Max(x,y: Int64): Int64; overload; begin end;' + LineEnding +
'function Max(x,y: Extended): Extended; overload; begin end;' + LineEnding +
'function Abs(x: Extended): Extended; overload; begin end;' + LineEnding +
'function Abs(x: Int64): Int64; overload; begin end;' + LineEnding +
'function Sign(AValue: Int64): Int8; overload; begin end;' + LineEnding +
'function Sign(AValue: Extended): Int8; overload; begin end;' + LineEnding +
'function Power(Base, Exponent: Extended): Extended; begin end;' + LineEnding +
'function Sqr(x: Extended): Extended; overload; begin end;' + LineEnding +
'function Sqr(x: Int64): Int64; overload; begin end;' + LineEnding +
'function Sqrt(x: Extended): Extended; begin end;' + LineEnding +
'function ArcTan(x: Extended): Extended; begin end;' + LineEnding +
'function Ln(x: Extended): Extended; begin end;' + LineEnding +
'function Sin(x: Extended): Extended; begin end;' + LineEnding +
'function Cos(x: Extended): Extended; begin end;' + LineEnding +
'function Exp(x: Extended): Extended; begin end;' + LineEnding +
'function Hypot(x,y: Extended): Extended; begin end;' + LineEnding +
'function ArcTan2(x,y: Extended): Extended; begin end;' + LineEnding +
'function Tan(x: Extended): Extended; begin end;' + LineEnding +
'function ArcSin(x: Extended): Extended; begin end;' + LineEnding +
'function ArcCos(x: Extended): Extended; begin end;' + LineEnding +
'function Cotan(x: Extended): Extended; begin end;' + LineEnding +
'function Secant(x: Extended): Extended; begin end;' + LineEnding +
'function Cosecant(x: Extended): Extended; begin end;' + LineEnding +
'function Round(x: Extended): Int64; overload; begin end;' + LineEnding +
'function Round(x: Extended; Precision: Int8): Extended; overload; begin end;' + LineEnding +
'function Frac(x: Extended): Extended; begin end;' + LineEnding +
'function Int(x: Extended): Extended; begin end;' + LineEnding +
'function Trunc(x: Extended): Int64; begin end;' + LineEnding +
'function Ceil(x: Extended): Int64; begin end;' + LineEnding +
'function Floor(x: Extended): Int64; begin end;' + LineEnding +
'function CosH(x: Extended): Extended; begin end;' + LineEnding +
'function SinH(x: Extended): Extended; begin end;' + LineEnding +
'function TanH(x: Extended): Extended; begin end;' + LineEnding +
'function ArcCosH(x: Extended): Extended; begin end;' + LineEnding +
'function ArcSinH(x: Extended): Extended; begin end;' + LineEnding +
'function ArcTanH(x: Extended): Extended; begin end;' + LineEnding;
