{
  Author: Raymond van Venetië and Merlijn Wajer
  Project: Simba (https://github.com/MerlijnWajer/Simba)
  License: GNU General Public License (https://www.gnu.org/licenses/gpl-3.0)
  --------------------------------------------------------------------------

  Simple crude pixel font ocr. "Pixel font" being "block text/zero antialiasing" and completely fixed font set.
  Every pixel of the glyph must match for for a character to be recognized.

  Orginally was SimpleOCR found at https://github.com/ollydev/SimpleOCR
}
unit simba.pixelocr;

{$i simba.inc}
{.$DEFINE DebugOutOfRange}

interface

uses
  Classes, SysUtils,
  simba.base,
  simba.image;

type
  TPixelFontGlyph = record
    Value: Char;

    Width: Int16;  // image width
    Height: Int16; // image height
    ForegroundBounds: TBox;  // foreground meaning points and shadow

    Points: TPointArray;      // character "white pixels" (note: x axis is offset from the image to not have background padding)
    Shadow: TPointArray;      // optional Shadow "red pixels" (note: x axis is offset from the image to not have background padding)
    Background: TPointArray;  // background "black pixels" of above generated by `TPointArray(Glyph.Points + Glyph.Shadow).Invert(B.Expand(1))`
    BackgroundBounds: TBox;   // bounds of above
    PointsShadowWidth: Int16; // width of points+shadow

    BestMatch: Int16; // best possible match
  end;
  PPixelFontGlyph = ^TPixelFontGlyph;

  TPixelFont = record
    Glyphs: array of TPixelFontGlyph;
    // Store similaries to each other glyph in the set.
    // Stored as a byte for memory optimization. (worst case if 255 glyphs = 64KB, aka nothing)
    // Tiny bit of accuracy lost, but nothing really. `val / 255` to get single value back.
    // If width and height between two glyphs aren't exactly the same the match is 0.
    GlyphSimilarities: array of TByteArray;

    SpaceWidth: Integer;
    MaxGlyphWidth: Integer;
    MaxGlyphHeight: Integer;
  end;
  PPixelFont = ^TPixelFont;

  TPixelOCRMatch = record
    Text: String;
    Hits: Integer;
    Bounds: TBox;
  end;

  TPixelOCR = record
    Tolerance: Single;
    ShadowTolerance: Single;
    Whitelist: set of Char;
    MaxWalk: Integer;
    MaxLen: Integer;
    Matches: array of TPixelOCRMatch;
  private
    function _RecognizeX(const Image: TSimbaImage; const Font: PPixelFont; X, Y: Integer; const isBinary: Boolean): TPixelOCRMatch;
    function _RecognizeXY(const Image: TSimbaImage; const Font: PPixelFont; X, Y, Height: Integer; const isBinary: Boolean): TPixelOCRMatch;
  public
    class function LoadFont(Dir: String; SpaceWidth: Integer): TPixelFont; static;
    class function LoadFont(const Images: TSimbaImageArray; SpaceWidth: Integer): TPixelFont; overload; static;
    class function TextToTPA(constref Font: TPixelFont; Text: String; out Background: TPointArray): TPointArray; static;
    class function TextToTPA(constref Font: TPixelFont; Text: String): TPointArray; overload; static;

    function Locate(Image: TSimbaImage; constref Font: TPixelFont; Text: String): Single;

    function Recognize(Image: TSimbaImage; constref Font: TPixelFont; P: TPoint): String; overload;
    function Recognize(Image: TSimbaImage; constref Font: TPixelFont; Bounds: TBox): String; overload;
    function RecognizeLines(Image: TSimbaImage; constref Font: TPixelFont; Bounds: TBox): TStringArray;
  end;

const
  ALPHA_NUM_SYMBOLS = ['a'..'z', 'A'..'Z', '0'..'9', '%', '&', '#', '$', '[', ']', '{', '}', '@', '!', '?'];

  // lookup table for above
  ALPHA_NUM_MAP: array[Char] of UInt8 = (
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
  );

implementation

uses
  simba.vartype_string,
  simba.vartype_box,
  simba.vartype_pointarray,
  simba.fs;

function IsSimilar(const Image: TSimbaImage; const X, Y: Integer; const Color2: TColorBGRA; const Tol: Single): Boolean; inline;
const
  MAX_DISTANCE_RGB = Single(441.672955930064); // Sqrt(Sqr(255) + Sqr(255) + Sqr(255))
begin
  with Image.Data[Y * Image.Width + X] do
    Result := (Sqrt(Sqr(R-Color2.R) + Sqr(G-Color2.G) + Sqr(B-Color2.B)) / MAX_DISTANCE_RGB * 100) <= Tol;
end;

function IsShadow(const Image: TSimbaImage; const X, Y: Integer; const Tol: Single): Boolean; inline;
begin
  with Image.Data[Y * Image.Width + X] do
    Result := (R <= Tol) and (G <= Tol) and (B <= Tol + 5); // allow a little more in the blue channel only
end;

function GetGlyph(const Font: PPixelFont; const c: Char): PPixelFontGlyph; inline;
var
  I: Integer;
begin
  for I := 0 to High(Font^.Glyphs) do
    if (Font^.Glyphs[I].Value = c) then
      Exit(@Font^.Glyphs[I]);

  SimbaException('Character %s does exist in the Font', [c]);
  Result := nil;
end;

// text contains >= 50% alphanum
function IsAlphaNumSym(const Text: String): Boolean; inline;
var
  Len, Count, Threshold: Integer;
  Ptr: PChar;
  Upper: PtrUInt;
begin
  Len := Length(Text);
  if (Len > 1) then
  begin
    Count := 0;
    Threshold := Len div 2;

    Ptr := @Text[1];
    Upper := PtrUInt(@Text[Len]);
    while (PtrUInt(Ptr) <= Upper) and (Count < Threshold) do
    begin
      Inc(Count, ALPHA_NUM_MAP[Ptr^]);
      Inc(Ptr);
    end;
    Result := Count >= Threshold;
  end else
    Result := False;
end;

function TPixelOCR._RecognizeX(const Image: TSimbaImage; const Font: PPixelFont; X, Y: Integer; const isBinary: Boolean): TPixelOCRMatch;

  function CompareUsingBackground(const Glyph: PPixelFontGlyph; const X, Y: Integer): Integer; inline;
  var
    FirstPixel: TColorBGRA;
    I, Misses, Bad: Integer;
  begin
    {$IFDEF DebugOutOfRange}
    for I := 0 to High(Glyph^.Points) do
      if (not InRange(Glyph^.Points[I].X + X, 0, Image.Width-1)) or (not InRange(Glyph^.Points[I].Y + Y, 0, Image.Height-1)) then
        SimbaException('Out of range!');
    for I := 0 to High(Glyph^.Shadow) do
      if (not InRange(Glyph^.Shadow[I].X + X, 0, Image.Width-1)) or (not InRange(Glyph^.Shadow[I].Y + Y, 0, Image.Height-1)) then
        SimbaException('Out of range!');
    {$ENDIF}

    case isBinary of
       True:
         begin
           // binary is simple, check all points are white
           for I := 0 to High(Glyph^.Points) do
             with Image.Data[(Glyph^.Points[I].Y + Y) * Image.Width + (Glyph^.Points[I].X + X)] do
               if (B <> 255) or (G <> 255) or (R <> 255) then
                 Exit(-1);

           // then deduct background points that are white
           // if < 50% its not a match.
           Bad := High(Glyph^.Background) div 2;
           Misses := 0;
           for I := 0 to High(Glyph^.Background) do
             with Image.Data[(Glyph^.Background[I].Y + Y) * Image.Width + (Glyph^.Background[I].X + X)] do
               if (B <> 0) or (G <> 0) or (R <> 0) then
               begin
                 Inc(Misses);
                 if (Misses > Bad) then
                   Exit(-1);
               end;
         end;

       False:
         begin
           // check all points match the first point color
           FirstPixel := Image.Data[(Glyph^.Points[0].Y + Y) * Image.Width + (Glyph^.Points[0].X + X)];
           for I := 1 to High(Glyph^.Points) do
             if not IsSimilar(Image, Glyph^.Points[I].X + X, Glyph^.Points[I].Y + Y, FirstPixel, Tolerance) then
               Exit(-1);

           // then deduct background points that match the first point color
           // if < 50% its not a match.
           Bad := High(Glyph^.Background) div 2;
           Misses := 0;
           for I := 0 to High(Glyph^.Background) do
             if IsSimilar(Image, Glyph^.Background[I].X + X, Glyph^.Background[I].Y + Y, FirstPixel, Tolerance) then
             begin
               Inc(Misses);
               if (Misses > Bad) then
                 Exit(-1);
             end;
         end;
     end;

     Result := Glyph^.BestMatch - Misses;
  end;

  function CompareUsingShadow(const Glyph: PPixelFontGlyph; const X, Y: Integer): Integer; inline;
  var
    FirstPixel: TColorBGRA;
    I: Integer;
  begin
    {$IFDEF DebugOutOfRange}
    for I := 0 to High(Glyph^.Points) do
      if (not InRange(Glyph^.Points[I].X + X, 0, Image.Width-1)) or (not InRange(Glyph^.Points[I].Y + Y, 0, Image.Height-1)) then
        SimbaException('Out of range!');
    for I := 0 to High(Glyph^.Shadow) do
      if (not InRange(Glyph^.Shadow[I].X + X, 0, Image.Width-1)) or (not InRange(Glyph^.Shadow[I].Y + Y, 0, Image.Height-1)) then
        SimbaException('Out of range!');
    {$ENDIF}

    case isBinary of
      True:
        begin
          // binary is simple - check all points are white
          for I := 0 to High(Glyph^.Points) do
            with Image.Data[(Glyph^.Points[I].Y + Y) * Image.Width + (Glyph^.Points[I].X + X)] do
              if (B <> 255) or (G <> 255) or (R <> 255) then
                Exit(-1);

          // and shadows are 0
          for I := 0 to High(Glyph^.Shadow) do
            with Image.Data[(Glyph^.Shadow[I].Y + Y) * Image.Width + (Glyph^.Shadow[I].X + X)] do
              if (B <> 0) or (G <> 0) or (R <> 0) then
                Exit(-1);
        end;

      False:
        begin
          // if the first pixel is a dark'ish color its a non starter
          if IsShadow(Image, Glyph^.Points[0].X + X, Glyph^.Points[0].Y + Y, Self.shadowTolerance * 2) then
            Exit(-1);

          // check all shadows are shadows
          for I := 0 to High(Glyph^.Shadow) do
            if not IsShadow(Image, Glyph^.Shadow[I].X + X, Glyph^.Shadow[I].Y + Y, self.shadowTolerance) then
              Exit(-1);

          // Always use first pixel to compare against
          FirstPixel := Image.Data[(Glyph^.Points[0].Y + Y) * Image.Width + (Glyph^.Points[0].X + X)];
          // check all other Points match the first pixel
          for I := 1 to High(Glyph^.Points) do
            if not IsSimilar(Image, Glyph^.Points[I].X + X, Glyph^.Points[I].Y + Y, FirstPixel, Tolerance) then
              Exit(-1);
        end;
    end;

    Result := Glyph^.BestMatch;
  end;

var
  Space: Integer;
  Hits, BestHits: Integer;
  Lo, Hi: PPixelFontGlyph;
  Glyph, BestGlyph: PPixelFontGlyph;
begin
  Result := Default(TPixelOCRMatch);
  Result.Bounds.X1 := $FFFFFF;
  Result.Bounds.Y1 := $FFFFFF;
  Space := 0;

  Lo := @Font^.Glyphs[0];
  Hi := @Font^.Glyphs[High(Font^.Glyphs)];

  while (X < Image.Width) and ((MaxWalk = 0) or (Space < MaxWalk)) do
  begin
    BestHits := 0;

    Glyph := Lo;
    while (PtrUInt(Glyph) <= PtrUInt(Hi)) do
    begin
      if (Glyph^.Points <> nil) and
         (X + Glyph^.BackgroundBounds.X1 >= 0) and (X + Glyph^.BackgroundBounds.X2 < Image.Width) and
         (Y + Glyph^.BackgroundBounds.Y1 >= 0) and (Y + Glyph^.BackgroundBounds.Y2 < Image.Height) then
      begin
        if (Glyph^.Shadow <> nil) then
          Hits := CompareUsingShadow(Glyph, X, Y)
        else
          Hits := CompareUsingBackground(Glyph, X, Y);

        if (Hits > BestHits) then
        begin
          BestGlyph := Glyph;
          BestHits := Hits;
        end;
      end;

      Inc(Glyph);
    end;

    if (BestHits > 0) then
    begin
      if ((WhiteList = []) or ({%H-}BestGlyph^.Value in Self.Whitelist)) then
      begin
        if (Result.Text <> '') and (Space >= Font^.SpaceWidth) then
          Result.Text += ' ';

        with Result.Bounds do
        begin
          X1 := Min(X1, X);
          Y1 := Min(Y1, Y + BestGlyph^.ForegroundBounds.Y1);
          X2 := Max(X2, X + BestGlyph^.PointsShadowWidth);
          Y2 := Max(Y2, Y + BestGlyph^.ForegroundBounds.Y2);
        end;

        Result.Text += BestGlyph^.Value;
        Result.Hits += BestHits;

        if (MaxLen >= Length(Result.Text)) then
          Exit;
      end;

      Space := 0;
      X += BestGlyph^.PointsShadowWidth;
    end else
    begin
      Space += 1;
      X += 1;
    end;
  end;
end;

function TPixelOCR._RecognizeXY(const Image: TSimbaImage; const Font: PPixelFont; X, Y, Height: Integer; const isBinary: Boolean): TPixelOCRMatch;
var
  Stop: Integer;
  Match: TPixelOCRMatch;
begin
  Result := Default(TPixelOCRMatch);

  Stop := Y + Height;
  while (Y < Stop) do
  begin
    Match := Self._RecognizeX(Image, Font, X, Y, isBinary);
    if (Match.Hits > Result.Hits) then
      Result := Match;

    Y += 1;
  end;
end;

function GlyphSimilarity(const A, B: TPixelFontGlyph): Single;
var
  Img: TByteArray;
  P: TPoint;
  Hit, Miss: Integer;
begin
  if (A.Width <> B.Width) or (A.Height <> B.Height) or (A.Width = 0) then
    Exit(0.0);

  SetLength(Img, A.Width * A.Height);
  for P in A.Points do
    Img[P.Y * A.Width + P.X] := 255;

  Hit := 0;
  for P in B.Points do
    if Img[P.Y * A.Width + P.X] = 255 then
      Inc(Hit);
  Miss := Length(A.Points) + Length(B.Points) - (2 * Hit);

  Result := 1.0 - (Miss / Length(Img));
end;

class function TPixelOCR.LoadFont(Dir: String; SpaceWidth: Integer): TPixelFont;
var
  Image: TSimbaImage;
  Files: TStringArray;
  I,J, Count: Integer;
  Character: String;
  Glyph: TPixelFontGlyph;
  B: TBox;
begin
  Result := Default(TPixelFont);
  Result.SpaceWidth := SpaceWidth;

  Files := TSimbaDir.DirList(dir);
  if (Length(Files) = 0) then
    Exit;
  SetLength(Result.Glyphs, Length(Files));
  Count := 0;

  Image := TSimbaImage.Create();
  try
    for I := 0 to High(Files) do
    begin
      if not TSimbaPath.PathHasExt(Files[I], ['.bmp', '.png']) then
        Continue;

      Character := TSimbaPath.PathExtractNameWithoutExt(Files[I]);
      if Character.IsNumeric and (Character.ToInt >= 32) and (Character.ToInt <= 126) then
      begin
        Image.Load(Files[I]);

        Glyph := Default(TPixelFontGlyph);
        Glyph.Value := Char(Character.ToInt);
        Glyph.Width := Image.Width;
        Glyph.Height := Image.Height;
        if (Glyph.Value > #32) then // not a space
        begin
          Glyph.Points := Image.FindColor($FFFFFF, 0, TBox.Create(-1,-1,-1,-1));
          if (Length(Glyph.Points) = 0) then // if not a space, must have points otherwise skip
            Continue;
          Glyph.Shadow := Image.FindColor($0000FF, 0, TBox.Create(-1,-1,-1,-1));
          Glyph.ForegroundBounds := TPointArray(Glyph.Points + Glyph.Shadow).Bounds;

          B := Glyph.Points.Bounds;
          if (B.X1 > 0) then
          begin
            Glyph.Points := Glyph.Points.Offset(-B.X1, 0);
            Glyph.Shadow := Glyph.Shadow.Offset(-B.X1, 0);
          end;
          B := TPointArray(Glyph.Points + Glyph.Shadow).Bounds;

          Glyph.Background := TPointArray(Glyph.Points + Glyph.Shadow).Invert(B.Expand(1));
          Glyph.BackgroundBounds := B;
          Glyph.PointsShadowWidth := B.Width;

          if (Length(Glyph.Shadow) > 0) then
            Glyph.BestMatch := Length(Glyph.Points) + Length(Glyph.Shadow)
          else
            Glyph.BestMatch := Length(Glyph.Points) + Length(Glyph.Background);

          Result.MaxGlyphWidth := Max(Result.MaxGlyphWidth, Glyph.Background.Bounds.Width-1);
          Result.MaxGlyphHeight := Max(Result.MaxGlyphHeight, Glyph.Background.Bounds.Height-1);
        end;

        Result.Glyphs[Count] := Glyph;
        Inc(Count);
      end;
    end;
  finally
    SetLength(Result.Glyphs, Count);

    Image.Free();
  end;

  SetLength(Result.GlyphSimilarities, Count, Count);
  for I := 0 to Count-1 do
    for J := 0 to Count-1 do
      if (I <> J) then
        Result.GlyphSimilarities[I][J] := Round(GlyphSimilarity(Result.Glyphs[I], Result.Glyphs[J]) * 255);
end;

class function TPixelOCR.LoadFont(const Images: TSimbaImageArray; SpaceWidth: Integer): TPixelFont;
var
  Image: TSimbaImage;
  Files: TStringArray;
  I,J, Count: Integer;
  Character: String;
  Glyph: TPixelFontGlyph;
  B: TBox;
begin
  Result := Default(TPixelFont);
  Result.SpaceWidth := SpaceWidth;

  if (Length(Images) <> 255) then
    Exit;
  SetLength(Result.Glyphs, 255);
  Count := 0;

  Image := TSimbaImage.Create();
  try
    for I := 0 to High(Images) do
    begin
        Image := Images[I];
        Glyph := Default(TPixelFontGlyph);
        Glyph.Value := Char(I);
        Glyph.Width := Image.Width;
        Glyph.Height := Image.Height;
        if (Glyph.Value > #32) then // not a space
        begin
          Glyph.Points := Image.FindColor($FFFFFF, 0, TBox.Create(-1,-1,-1,-1));
          if (Length(Glyph.Points) = 0) then // if not a space, must have points otherwise skip
            Continue;
          Glyph.Shadow := Image.FindColor($0000FF, 0, TBox.Create(-1,-1,-1,-1));
          Glyph.ForegroundBounds := TPointArray(Glyph.Points + Glyph.Shadow).Bounds;

          B := Glyph.Points.Bounds;
          if (B.X1 > 0) then
          begin
            Glyph.Points := Glyph.Points.Offset(-B.X1, 0);
            Glyph.Shadow := Glyph.Shadow.Offset(-B.X1, 0);
          end;
          B := TPointArray(Glyph.Points + Glyph.Shadow).Bounds;

          Glyph.Background := TPointArray(Glyph.Points + Glyph.Shadow).Invert(B.Expand(1));
          Glyph.BackgroundBounds := B;
          Glyph.PointsShadowWidth := B.Width;

          if (Length(Glyph.Shadow) > 0) then
            Glyph.BestMatch := Length(Glyph.Points) + Length(Glyph.Shadow)
          else
            Glyph.BestMatch := Length(Glyph.Points) + Length(Glyph.Background);

          Result.MaxGlyphWidth := Max(Result.MaxGlyphWidth, Glyph.Background.Bounds.Width-1);
          Result.MaxGlyphHeight := Max(Result.MaxGlyphHeight, Glyph.Background.Bounds.Height-1);
        end;

        Result.Glyphs[Count] := Glyph;
        Inc(Count);
    end;
  finally
    SetLength(Result.Glyphs, Count);
  end;

  SetLength(Result.GlyphSimilarities, Count, Count);
  for I := 0 to Count-1 do
    for J := 0 to Count-1 do
      if (I <> J) then
        Result.GlyphSimilarities[I][J] := Round(GlyphSimilarity(Result.Glyphs[I], Result.Glyphs[J]) * 255);
end;

class function TPixelOCR.TextToTPA(constref Font: TPixelFont; Text: String; out Background: TPointArray): TPointArray;
var
  I, J, X, Count: Integer;
  MinY, MaxY, MaxX: Integer;
begin
  MinY := $FFFFFF;
  MaxY := 0;
  MaxX := 0;

  X := 0;
  Count := 0;
  for I := 1 to Length(Text) do
    with GetGlyph(@Font, Text[I])^ do
    begin
      if (Points <> nil) then
      begin
        Inc(Count, Length(Points));

        if (ForegroundBounds.Y2 > MaxY) then
          MaxY := ForegroundBounds.Y2;
        if (ForegroundBounds.Y1 < MinY) then
          MinY := ForegroundBounds.Y1;
      end;

      MaxX += Width;
    end;
  SetLength(Result, Count);

  Count := 0;
  for I := 1 to Length(Text) do
    with GetGlyph(@Font, Text[I])^ do
    begin
      for J := 0 to High(Points) do
      begin
        Result[Count].X := Points[J].X + (X + ForegroundBounds.X1);
        Result[Count].Y := Points[J].Y - MinY;

        Inc(Count);
      end;
      Inc(X, Width);
    end;

  Background := Result.Invert(TBox.Create(0, 0, MaxX, MaxY-MinY));
end;

class function TPixelOCR.TextToTPA(constref Font: TPixelFont; Text: String): TPointArray;
var
  _: TPointArray;
begin
  Result := TPixelOCR.TextToTPA(Font, Text, _);
end;

function TPixelOCR.Locate(Image: TSimbaImage; constref Font: TPixelFont; Text: String): Single;
var
  X, Y: Integer;
  Bad, I, BackgroundLen: Integer;
  SearchWidth, SearchHeight: Integer;
  Match: Single;
  BestMatch: TPixelOCRMatch;
  First: TColorBGRA;
  Points, Background: TPointArray;
label
  NotFoundBinary, NotFoundColor, Finished;
begin
  Result := 0;
  Matches := [];

  Points := TextToTPA(Font, Text, Background);
  BackgroundLen := Length(Background);
  if (Length(Points) = 0) or (Length(Background) = 0) then
    Exit;

  SearchHeight := Image.Height - Background.Bounds.Height;
  SearchWidth := Image.Width - Background.Bounds.Width;

  case Image.isBinary() of
    True:
      for Y := 0 to SearchHeight do
        for X := 0 to SearchWidth do
        begin
          for I := 0 to High(Points) do
            with Image.Data[(Points[I].Y + Y) * Image.Width + (Points[I].X + X)] do
              if (B <> 255) or (G <> 255) or (R <> 255) then
                goto NotFoundBinary;

          Bad := 0;
          for I := 0 to High(Background) do
            with Image.Data[(Background[I].Y + Y) * Image.Width + (Background[I].X + X)] do
              if (B <> 0) or (G <> 0) or (R <> 0) then
                Inc(Bad);

          Match := 1 - (Bad / BackgroundLen);
          if (Match > Result) then
          begin
            Result := Match;

            BestMatch.Bounds.X1 := X;
            BestMatch.Bounds.Y1 := Y;

            if (Result = 1) then
              goto Finished;
          end;

          NotFoundBinary:
        end;

    False:
      for Y := 0 to SearchHeight do
        for X := 0 to SearchWidth do
        begin
          First := Image.Data[(Y + Points[0].Y) * Image.Width + (X + Points[0].X)];
          for I := 1 to High(Points) do
            if (not IsSimilar(Image, X + Points[I].X, Y + Points[I].Y, First, Tolerance)) then
              goto NotFoundColor;

          Bad := 0;
          for I := 0 to High(Background) do
            if IsSimilar(Image, X + Background[I].X, Y + Background[I].Y, First, Tolerance) then
              Inc(Bad);

          Match := 1 - (Bad / BackgroundLen);
          if (Match > Result) then
          begin
            Result := Match;

            BestMatch.Bounds.X1 := X;
            BestMatch.Bounds.Y1 := Y;

            if (Result = 1) then
              goto Finished;
          end;

          NotFoundColor:
        end;
  end;

  Finished:

  if (Result > 0) then
  begin
    BestMatch.Hits := Round(Result * 100);
    BestMatch.Text := Text;
    BestMatch.Bounds.X2 := BestMatch.Bounds.X1 + Points.Bounds.Width;
    BestMatch.Bounds.Y2 := BestMatch.Bounds.Y1 + Points.Bounds.Height;

    Matches := [BestMatch];
  end else
    Matches := [Default(TPixelOCRMatch)];
end;

function TPixelOCR.Recognize(Image: TSimbaImage; constref Font: TPixelFont; P: TPoint): String; overload;
begin
  if (Length(Font.Glyphs) = 0) then
    SimbaException('Font is empty');

  Matches := [Self._RecognizeX(Image, @Font, P.X, P.Y, Image.isBinary)];
  Result := Matches[0].Text;
end;

function TPixelOCR.Recognize(Image: TSimbaImage; constref Font: TPixelFont; Bounds: TBox): String; overload;
begin
  if (Length(Font.Glyphs) = 0) then
    SimbaException('Font is empty');
  if (Bounds.X1 = -1) and (Bounds.Y1 = -1) and (Bounds.X2 = -1) and (Bounds.Y2 = -1) then
    Bounds := TBox.Create(0, 0, Image.Width-1, Image.Height-1);

  // decrease y a little as these are not normalized like X
  Bounds.Y1 -= Font.MaxGlyphHeight div 3;

  Matches := [Self._RecognizeXY(Image, @Font, Bounds.X1, Bounds.Y1, Bounds.Height, Image.isBinary)];
  Result := Matches[0].Text;
end;

function TPixelOCR.RecognizeLines(Image: TSimbaImage; constref Font: TPixelFont; Bounds: TBox): TStringArray;
var
  Temp: TPixelOCR;

  function MaybeRecognize(const X, Y: Integer; const isBinary: Boolean; out Match: TPixelOCRMatch): Boolean;
  begin
    // OCR the row and some extra rows that being `Font.MaxGlyphHeight div 2`
    Match := Temp._RecognizeXY(Image, @Font, X, Y, Font.MaxGlyphHeight div 2, isBinary);
    // Ensure that actual text was extracted, not just a symbol mess of short or small character symbols.
    Result := IsAlphaNumSym(Match.Text);
  end;

var
  isBinary: Boolean;
  Match: TPixelOCRMatch;
begin
  if (Length(Font.Glyphs) = 0) then
    SimbaException('Font is empty');

  Temp := Self;
  Temp.Whitelist := Self.Whitelist;
  Temp.MaxWalk := 0;
  Temp.MaxLen := 0;

  Result := [];
  Matches := [];

  isBinary := Image.isBinary;
  if (Bounds.X1 = -1) and (Bounds.Y1 = -1) and (Bounds.X2 = -1) and (Bounds.Y2 = -1) then
    Bounds := TBox.Create(0, 0, Image.Width-1, Image.Height-1);

  // decrease y a little as these are not normalized like X
  Bounds.Y1 -= Font.MaxGlyphHeight div 3;

  while (Bounds.Y1 < Bounds.Y2) do
  begin
    if MaybeRecognize(Bounds.X1, Bounds.Y1, isBinary, Match) then
    begin
      Result += [Match.Text];
      Matches += [Match];

      // Now we can confidently skip this search line by a jump, but we dont skip fully in case of close/overlapping Text
      // So we divide the texts max glyph Height by 2 and subtract that from the lower end of the found bounds.
      Bounds.Y1 := Max(Bounds.Y1+1, Match.Bounds.Y2 - (Font.MaxGlyphHeight div 2));
    end else
      Bounds.Y1 += 1;
  end;
end;

end.
