name: archive

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed    

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_repository.full_name == 'Villavu/Simba' && !startsWith(github.event.workflow_run.head_branch, 'dev/')
    runs-on: ubuntu-latest
    concurrency: archive-push
    permissions:
      actions: read
      contents: read
    steps:     
      - name: Download artifacts
        uses: actions/github-script@v7
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            for (artifact of allArtifacts.data.artifacts) {
              let download = await github.rest.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: artifact.id,
                 archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(artifact.name + '.zip', Buffer.from(download.data));
              console.log('Downloaded: ' + artifact.name);
            }

      - name: Push
        shell: bash     
        env:
          BRANCH: ${{ github.event.workflow_run.head_branch }}
          SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          git config --global http.postBuffer 500M
          git config --global user.email "villavu-bot"
          git config --global user.name "villavu-bot"
          git clone --depth 1 https://github.com/Villavu/Simba-Build-Archive

          echo "Current repo (uncompressed) size:"
          du -sh "Simba-Build-Archive" | awk '{print $1}'

          date_year=$(date +"%Y")
          date_month_day=$(date +"%m-%d")

          branch="$BRANCH"
          sha="$SHA"
          commit=${sha::10}
          url="$date_year/$date_month_day%20$branch%20$commit"

          row="$date_year/$date_month_day | $branch | [$commit](https://github.com/Villavu/Simba/commit/$commit) | "
          row+="[Win32](/$url/Simba_windows_i386.exe.zip?raw=true) - "
          row+="[Win64](/$url/Simba_windows_x86_64.exe.zip?raw=true) - "
          row+="[Win64&nbsp;Debug](/$url/Simba_windows_x86_64_debug.exe.zip?raw=true)<br>"
          row+="[Mac](/$url/Simba_darwin_x86_64.zip?raw=true) - "
          row+="[Mac Arm](/$url/Simba_darwin_aarch64.zip?raw=true)<br>"
          row+="[Linux](/$url/Simba_linux_x86_64.zip?raw=true) - "
          row+="[Linux Arm](/$url/Simba_linux_aarch64.zip?raw=true)"
          
          cd Simba-Build-Archive
          mkdir -p "$date_year/$date_month_day $branch $commit"
          mv ../*.zip "$date_year/$date_month_day $branch $commit"

          sed -i "6r /dev/stdin" README.md <<< "$row"

          archive="https://github.com/Villavu/Simba-Build-Archive/blob/main/$url"
          echo "$archive/Simba_windows_i386.exe.zip?raw=true"   > latest.win32
          echo "$archive/Simba_windows_x86_64.exe.zip?raw=true" > latest.win64
          echo "$archive/Simba_linux_x86_64.zip?raw=true"       > latest.linux64
          echo "$archive/Simba_linux_aarch64.zip?raw=true"      > latest.linuxarm64
          echo "$archive/Simba_darwin_x86_64.zip?raw=true"      > latest.macintel
          echo "$archive/Simba_darwin_aarch64.zip?raw=true"     > latest.macarm64

          git add .
          git commit --message "$commit"
          git push https://${{ secrets.API_TOKEN_GITHUB }}@github.com/villavu/simba-build-archive